CREATE TABLE IF NOT EXISTS outlets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    businessName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    businessType VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
)AUTO_INCREMENT = 40000;